services:
  backend:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: src/Dockerfile
    container_name: ocr-django-backend
    volumes:
      - .:/app/backend/src
      - ../ml_models:/app/backend/ml_models
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "